M48
; DRILL file KiCad 10.0.3 date 2026-05-20T03:18:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-20T03:18:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.750
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C1.000
%
G90
G05
T1
X64.92Y-137.27
X65.065Y-130.895
X70.0Y-137.27
X70.145Y-130.895
T2
X83.0Y-132.73
X83.0Y-134.0
X83.0Y-135.27
T3
X86.2Y-120.27
X93.8Y-120.27
T4
X79.73Y-119.65
X82.27Y-119.65
T5
X71.96Y-145.77
X74.5Y-145.77
M30
